on: [push, pull_request]

name: Code Coverage

jobs:
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:

      - name: checkout source
        uses: actions/checkout@v2

      - name: check code coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}